### ISSUE TITLE
Map 0dp width/height in ConstraintLayout to fillMaxWidth()/fillMaxHeight()

### ISSUE THREAD

**Issue by pocmo** [pocmo/recompose#28]
Using `ConstraintLayout` you'd often set `android:layout_width` or `android:layout_height` of a `View` to `0dp` to let the ConstraintLayout stretch it based on the constraints. `ConstraintLayout()` doesn't behave that way if you add a `width(0.dp)` modifier. In that case we need to translate it to `fillMaxWidth()` or `fillMaxHeight()`.

For now we could just always translate `0dp` to `fillMaxWidth()` or `fillMaxHeight()` if the node has *any* constraint set.

**Comment by anesabml** [comment]
`ConstraintLayout()`'s equivalent to `android:layout_width="0dp"` is done throught the `constraintsAs` modifier ([Source](https://stackoverflow.com/questions/64313409/equivalent-of-constraint-layout-0dp)), Ex: 
```
Text(
    text = "This would be some text",
    style = TextStyle(
        color = Color.Black,
        fontSize = 18.sp,
    ),
    modifier = Modifier.constrainAs(title) {
        top.linkTo(parent.top)
        bottom.linkTo(parent.bottom)
        start.linkTo(checkbox.end)
        end.linkTo(icon.start)
        width = Dimension.fillToConstraints
    },
)
```
Can I work on this?

**Comment by pocmo** [comment]
Interesting, so we'd need to add `width = Dimension.fillToConstraints`?

> Can I work on this?

Sure! I'll assign you. :)

**Comment by anesabml** [comment]
> so we'd need to add width = Dimension.fillToConstraints?

Yes, exactly
> Sure! I'll assign you. :)

Thank you :)
