### ISSUE TITLE
TextView: Add support for android:maxLines

### ISSUE THREAD

**Issue by pocmo** [pocmo/recompose#74]
> **android:maxLines**
> Makes the TextView be at most this many lines tall. When used on an editable text, the inputType attribute's value must be combined with the textMultiLine flag for the maxLines attribute to apply. 

XML attribute:
https://developer.android.com/reference/android/widget/TextView?hl=en#attr_android:maxLines

Jetpack Compose:
```Kotlin
Text(
   ...
   maxLines = Int = Int.MAX_VALUE
   ...
)
```

We are parsing `TextView` here:
https://github.com/pocmo/recompose/blob/main/recompose-parser/src/main/kotlin/recompose/parser/xml/view/TextView.kt

And create a `TextViewNode` from it:
https://github.com/pocmo/recompose/blob/main/recompose-ast/src/main/kotlin/recompose/ast/view/TextViewNode.kt

And we turn the node into Kotlin code here:
https://github.com/pocmo/recompose/blob/main/recompose-composer/src/main/kotlin/recompose/composer/visitor/ComposingVisitor.kt#L82-L94

To solve this issue:
* Parse the attribute and add the value to `TextViewNode`. Probably a nullable `Int?` is needed.
* Add it to the list of parameters in `ComposingVisitor`.
* Add a test case to `ParserTest` and `ComposerTest`.

**Comment by anesabml** [comment]
Can I work on this?

**Comment by pocmo** [comment]
Yep! Assigned. :)

**Comment by jerryOkafor** [comment]
I need one too. I have been following with curiosity and now I want to contribute.

**Comment by pocmo** [comment]
@jerryOkafor Maybe issue #73 to start? I'll make sure to file some more issues today. :)

**Comment by jerryOkafor** [comment]
Sure. I will work on it.
