### ISSUE TITLE
Add support for Switch

### ISSUE THREAD

**Issue by pocmo** [pocmo/recompose#93]
XML:
https://developer.android.com/reference/android/widget/Switch

Composable:
?

**Comment by jerryOkafor** [comment]
@pocmo I have searched for the documentation of Compose Switch, I could not find anything. I am sure it exists because I have used it before:

```
val checkedState = remember { mutableStateOf(singlePlayer) }

    Switch(checked = checkedState.value, onCheckedChange = {
        checkedState.value = it
        onCheckedChange(it)
    })
```

**Comment by Foso** [comment]
https://foso.github.io/Jetpack-Compose-Playground/material/switch/
https://developer.android.com/reference/kotlin/androidx/compose/material/package-summary#switch
