### ISSUE TITLE
Add support for EditText attributes

### ISSUE THREAD

**Issue by anesabml** [pocmo/recompose#95]
Add support for these attributes: `android:hint`, `android:textColorHint`

**Comment by pocmo** [comment]
👍 

Depending on how complicated it is, we may want to file an issue for each of them. For example I assume `hint` will require to compose with a `Text()` and that could start getting complicated. :)

**Comment by anesabml** [comment]
Yes, I will create separate issues for each attribute.

**Comment by anesabml** [comment]
I would like to work on this, please!

**Comment by pocmo** [comment]
> Yes, I will create separate issues for each attribute, android:hint and android:textColorHint should be in one issue, right?

Yeah,  that makes sense. 👍 

> I would like to work on this, please!

Great, I'll assign it to you. :)
